<a href="https://colab.research.google.com/github/danielindrasm/danielinsm.github.io/blob/main/Klasifikasi_DataMNIST_HOG_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
from skimage.feature import hog
from skimage import exposure


# masuk ke dataset MNIST
digits = datasets.load_digits()

# Fitur extraction pada Hog
def extract_hog_features(images):
    features = []
    for image in images:
        fd, hog_image = hog(image.reshape((8, 8)), orientations=8, pixels_per_cell=(5, 5), cells_per_block=(1, 1), visualize=True)
        features.append(fd)
    return np.array(features)

# Membagi Dataset
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3, random_state=42)


# Fitur menggunakan HOG
x_train_hog = extract_hog_features(x_train)
x_test_hog  = extract_hog_features(x_test)


# Fitur yang sesuai dengan standarisai
scaler = StandardScaler().fit(x_train_hog)
x_train_hog = scaler.transform(x_train_hog)
x_test_hog = scaler.transform(x_test_hog)


# Train menggunakan SVM
svm_model = SVC(kernel='linear', C=1)
svm_model.fit(x_train_hog, y_train)


# Melakukan prediksi
y_pred = svm_model.predict(x_test_hog)

# Evaluasi performance
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

# Hasil yang di tampilkan
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Precision:", precision)


Accuracy: 0.3888888888888889
Confusion Matrix:
 [[13  1  5  0 12  4 12  0  4  2]
 [ 0 25  6  8  2  0  4  2  1  2]
 [ 0  1 15  3  0  3  3  9  4  9]
 [ 0  1 11 13  1  3  0  3  6 16]
 [ 5  1  4  0 32  2  3 10  1  2]
 [ 1  1  3  6  1 16  2  1  8 27]
 [ 8  0  4  0  9  1 19  5  6  1]
 [ 2  0  6  1  6  5  1 27  4  3]
 [ 8  0  3  2  0  6  3  3 10  8]
 [ 1  0  6  8  0  2  0  1  1 40]]
Precision: 0.4083511404873106
